name: tenants

services:
  postgres:
    image: postgres
    container_name: postgres-container-tenants
    ports:
      - "5420:5432"
    environment:
      POSTGRES_DB: tenants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


